#ifndef _OSMAND_CORE_COMMON_WORDS_H_
#define _OSMAND_CORE_COMMON_WORDS_H_

#include <OsmAndCore/stdlib_common.h>
#include <functional>

#include <QtGlobal>
#include <QString>
#include <QList>

#include <OsmAndCore.h>
#include <OsmAndCore/Common.h>
#include <OsmAndCore/QuickAccessors.h>

namespace OsmAnd
{
    const static QStringList WORDS {
        
        QStringLiteral("la"),
        QStringLiteral("via"),
        QStringLiteral("rua"),
        QStringLiteral("de"),
        QStringLiteral("du"),
        QStringLiteral("des"),
        QStringLiteral("del"),
        QStringLiteral("am"),
        QStringLiteral("da"),
        QStringLiteral("a"),
        QStringLiteral("der"),
        QStringLiteral("do"),
        QStringLiteral("los"),
        QStringLiteral("di"),
        QStringLiteral("im"),
        QStringLiteral("el"),
        QStringLiteral("e"),
        QStringLiteral("an"),
        QStringLiteral("g."),
        QStringLiteral("rd"),
        QStringLiteral("dos"),
        QStringLiteral("dei"),
        QStringLiteral("b"),
        QStringLiteral("st"),
        QStringLiteral("the"),
        QStringLiteral("las"),
        QStringLiteral("f"),
        QStringLiteral("u"),
        QStringLiteral("jl."),
        QStringLiteral("j"),
        QStringLiteral("sk"),
        QStringLiteral("w"),
        QStringLiteral("a."),
        QStringLiteral("of"),
        QStringLiteral("k"),
        QStringLiteral("r"),
        QStringLiteral("h"),
        QStringLiteral("mc"),
        QStringLiteral("sw"),
        QStringLiteral("g"),
        QStringLiteral("v"),
        QStringLiteral("m"),
        QStringLiteral("c."),
        QStringLiteral("r."),
        QStringLiteral("ct"),
        QStringLiteral("e."),
        QStringLiteral("dr."),
        QStringLiteral("j."),
        QStringLiteral("in"),
        QStringLiteral("al"),
        QStringLiteral("út"),
        QStringLiteral("per"),
        QStringLiteral("ne"),
        QStringLiteral("p"),
        QStringLiteral("et"),
        QStringLiteral("s."),
        QStringLiteral("f."),
        QStringLiteral("t"),
        QStringLiteral("fe"),
        QStringLiteral("à"),
        QStringLiteral("i"),
        QStringLiteral("c"),
        QStringLiteral("le"),
        QStringLiteral("s"),
        QStringLiteral("av."),
        QStringLiteral("den"),
        QStringLiteral("dr"),
        QStringLiteral("y"),
        QStringLiteral("un"),
        
        
        
        QStringLiteral("van"),
        QStringLiteral("road"),
        QStringLiteral("street"),
        QStringLiteral("drive"),
        QStringLiteral("avenue"),
        QStringLiteral("rue"),
        QStringLiteral("lane"),
        QStringLiteral("улица"),
        QStringLiteral("спуск"),
        QStringLiteral("straße"),
        QStringLiteral("chemin"),
        QStringLiteral("way"),
        
        QStringLiteral("court"),
        QStringLiteral("calle"),
        
        QStringLiteral("place"),
        
        QStringLiteral("avenida"),
        QStringLiteral("boulevard"),
        QStringLiteral("county"),
        QStringLiteral("route"),
        QStringLiteral("trail"),
        QStringLiteral("circle"),
        QStringLiteral("close"),
        QStringLiteral("highway"),
        
        QStringLiteral("strada"),
        QStringLiteral("impasse"),
        QStringLiteral("utca"),
        QStringLiteral("creek"),
        QStringLiteral("carrer"),
        QStringLiteral("вулиця"),
        QStringLiteral("allée"),
        QStringLiteral("weg"),
        QStringLiteral("площадь"),
        QStringLiteral("тупик"),
        
        QStringLiteral("terrace"),
        QStringLiteral("jalan"),
        
        QStringLiteral("parkway"),
        QStringLiteral("переулок"),
        
        QStringLiteral("carretera"),
        QStringLiteral("valley"),
        
        QStringLiteral("camino"),
        QStringLiteral("viale"),
        QStringLiteral("loop"),
        
        QStringLiteral("bridge"),
        QStringLiteral("embankment"),
        QStringLiteral("township"),
        QStringLiteral("town"),
        QStringLiteral("village"),
        QStringLiteral("piazza"),
        QStringLiteral("della"),
        
        QStringLiteral("plaza"),
        QStringLiteral("pasaje"),
        QStringLiteral("expressway"),
        QStringLiteral("ruta"),
        QStringLiteral("square"),
        QStringLiteral("freeway"),
        QStringLiteral("line"),
        
        QStringLiteral("track"),
        
        QStringLiteral("zum"),
        QStringLiteral("rodovia"),
        QStringLiteral("sokak"),
        QStringLiteral("sur"),
        QStringLiteral("path"),
        QStringLiteral("das"),
        
        QStringLiteral("yolu"),
        
        QStringLiteral("проспект"),
        
        QStringLiteral("auf"),
        QStringLiteral("alley"),
        QStringLiteral("são"),
        QStringLiteral("les"),
        QStringLiteral("delle"),
        QStringLiteral("paseo"),
        QStringLiteral("alte"),
        QStringLiteral("autostrada"),
        QStringLiteral("iela"),
        QStringLiteral("autovía"),
        QStringLiteral("d"),
        QStringLiteral("ulica"),
        
        QStringLiteral("na"),
        QStringLiteral("проезд"),
        QStringLiteral("n"),
        QStringLiteral("ул."),
        QStringLiteral("voie"),
        QStringLiteral("ring"),
        QStringLiteral("ruelle"),
        QStringLiteral("vicolo"),
        QStringLiteral("avinguda"),
        QStringLiteral("шоссе"),
        QStringLiteral("zur"),
        QStringLiteral("corso"),
        QStringLiteral("autopista"),
        QStringLiteral("провулок"),
        QStringLiteral("broadway"),
        QStringLiteral("to"),
        QStringLiteral("passage"),
        QStringLiteral("sentier"),
        QStringLiteral("aleja"),
        QStringLiteral("dem"),
        QStringLiteral("valle"),
        QStringLiteral("cruz"),
        
        QStringLiteral("bypass"),
        QStringLiteral("rúa"),
        QStringLiteral("crest"),
        QStringLiteral("ave"),
        
        QStringLiteral("expressway)"),
        
        QStringLiteral("autoroute"),
        QStringLiteral("crossing"),
        QStringLiteral("camí"),
        QStringLiteral("bend"),
        
        QStringLiteral("end"),
        QStringLiteral("caddesi"),
        QStringLiteral("bis"),
        
        QStringLiteral("ქუჩა"),
        QStringLiteral("kalea"),
        QStringLiteral("pass"),
        QStringLiteral("ponte"),
        QStringLiteral("cruce"),
        QStringLiteral("se"),
        QStringLiteral("au"),
        
        QStringLiteral("allee"),
        QStringLiteral("autobahn"),
        QStringLiteral("väg"),
        QStringLiteral("sentiero"),
        QStringLiteral("plaça"),
        QStringLiteral("o"),
        QStringLiteral("vej"),
        QStringLiteral("aux"),
        QStringLiteral("spur"),
        QStringLiteral("ringstraße"),
        QStringLiteral("prospect"),
        QStringLiteral("m."),
        QStringLiteral("chaussee"),
        QStringLiteral("row"),
        QStringLiteral("link"),
        
        QStringLiteral("travesía"),
        QStringLiteral("degli"),
        QStringLiteral("piazzale"),
        QStringLiteral("vei"),
        QStringLiteral("waldstraße"),
        QStringLiteral("promenade"),
        QStringLiteral("puente"),
        QStringLiteral("rond-point"),
        QStringLiteral("vía"),
        QStringLiteral("pod"),
        QStringLiteral("triq"),
        QStringLiteral("hwy"),
        QStringLiteral("οδός"),
        QStringLiteral("dels"),
        QStringLiteral("and"),
        
        QStringLiteral("pré"),
        QStringLiteral("plac"),
        QStringLiteral("fairway"),
        
        //      QStringLiteral("farm-to-market"),
        
        QStringLiteral("набережная"),
        
        QStringLiteral("chaussée"),
        
        QStringLiteral("náměstí"),
        QStringLiteral("tér"),
        QStringLiteral("roundabout"),
        QStringLiteral("lakeshore"),
        QStringLiteral("lakeside"),
        QStringLiteral("alle"),
        QStringLiteral("gasse"),
        QStringLiteral("str."),
        //      QStringLiteral("p."),
        QStringLiteral("ville"),
        QStringLiteral("beco"),
        QStringLiteral("platz"),
        
        //      QStringLiteral("porto"),
        
        QStringLiteral("sideroad"),
        QStringLiteral("pista"),
        
        QStringLiteral("аллея"),
        QStringLiteral("бульвар"),
        QStringLiteral("город"),
        QStringLiteral("городок"),
        QStringLiteral("деревня"),
        QStringLiteral("дер."),
        QStringLiteral("пос."),
        QStringLiteral("дорога"),
        QStringLiteral("дорожка"),
        QStringLiteral("кольцо"),
        QStringLiteral("мост"),
        QStringLiteral("остров"),
        QStringLiteral("островок"),
        QStringLiteral("поселок"),
        QStringLiteral("посёлок"),
        QStringLiteral("путепровод"),
        QStringLiteral("слобода"),
        QStringLiteral("станция"),
        QStringLiteral("тоннель"),
        QStringLiteral("тракт"),
        QStringLiteral("island"),
        QStringLiteral("islet"),
        QStringLiteral("tunnel"),
        QStringLiteral("stadt"),
        QStringLiteral("brücke"),
        QStringLiteral("damm"),
        QStringLiteral("insel"),
        QStringLiteral("dorf"),
        QStringLiteral("bereich"),
        QStringLiteral("überführung"),
        QStringLiteral("bulevar"),
        QStringLiteral("ciudad"),
        QStringLiteral("pueblo"),
        QStringLiteral("anillo"),
        QStringLiteral("muelle"),
        QStringLiteral("isla"),
        QStringLiteral("islote"),
        QStringLiteral("carril"),
        QStringLiteral("viaje"),
        QStringLiteral("città"),
        QStringLiteral("paese"),
        QStringLiteral("villaggio"),
        QStringLiteral("banchina"),
        QStringLiteral("isola"),
        QStringLiteral("isolotto"),
        QStringLiteral("corsia"),
        QStringLiteral("viaggio"),
        QStringLiteral("canale"),
        QStringLiteral("pont"),
        QStringLiteral("quai"),
        QStringLiteral("île"),
        QStringLiteral("îlot"),
        QStringLiteral("voyage"),
        QStringLiteral("descente"),
        QStringLiteral("straat"),
        QStringLiteral("stad"),
        QStringLiteral("dorp"),
        QStringLiteral("brug"),
        QStringLiteral("kade"),
        QStringLiteral("eiland"),
        QStringLiteral("eilandje"),
        QStringLiteral("laan"),
        QStringLiteral("plein"),
        QStringLiteral("reizen"),
        QStringLiteral("afkomst"),
        QStringLiteral("kanaal"),
        QStringLiteral("doodlopende"),
        QStringLiteral("stradă"),
        QStringLiteral("rutier"),
        QStringLiteral("alee"),
        QStringLiteral("municipiu"),
        QStringLiteral("oras"),
        QStringLiteral("drumuri"),
        QStringLiteral("poduri"),
        QStringLiteral("cheu"),
        QStringLiteral("insula"),
        QStringLiteral("ostrov"),
        QStringLiteral("sat"),
        QStringLiteral("călătorie"),
        QStringLiteral("coborâre"),
        QStringLiteral("statie"),
        QStringLiteral("tunel"),
        QStringLiteral("fundătură"),
        QStringLiteral("ulice"),
        QStringLiteral("silnice"),
        QStringLiteral("bulvár"),
        QStringLiteral("město"),
        QStringLiteral("obec"),
        QStringLiteral("most"),
        QStringLiteral("nábřeží"),
        QStringLiteral("ostrova"),
        QStringLiteral("ostrůvek"),
        QStringLiteral("lane"),
        QStringLiteral("vesnice"),
        QStringLiteral("jezdit"),
        QStringLiteral("sestup"),
        QStringLiteral("nádraží"),
        QStringLiteral("kanál"),
        QStringLiteral("ulička"),
        QStringLiteral("gata"),
        QStringLiteral("by"),
        QStringLiteral("bro"),
        QStringLiteral("kaj"),
        QStringLiteral("ö"),
        QStringLiteral("holme"),
        QStringLiteral("fyrkant"),
        QStringLiteral("resa"),
        QStringLiteral("härkomst"),
        QStringLiteral("kanal"),
        QStringLiteral("återvändsgränd"),
        QStringLiteral("cesty"),
        QStringLiteral("ostrovček"),
        QStringLiteral("námestie"),
        QStringLiteral("dediny"),
        QStringLiteral("jazdiť"),
        QStringLiteral("zostup"),
        QStringLiteral("stanice"),
        QStringLiteral("cesta"),
        QStringLiteral("pot"),
        QStringLiteral("mesto"),
        QStringLiteral("kraj"),
        QStringLiteral("vas"),
        QStringLiteral("pomol"),
        QStringLiteral("otok"),
        QStringLiteral("otoček"),
        QStringLiteral("trg"),
        QStringLiteral("potovanje"),
        QStringLiteral("spust"),
        QStringLiteral("postaja"),
        QStringLiteral("predor"),
        QStringLiteral("вуліца"),
        QStringLiteral("шаша"),
        QStringLiteral("алея"),
        QStringLiteral("горад"),
        QStringLiteral("мястэчка"),
        QStringLiteral("вёска"),
        QStringLiteral("дарога"),
        QStringLiteral("набярэжная"),
        QStringLiteral("востраў"),
        QStringLiteral("астравок"),
        QStringLiteral("завулак"),
        QStringLiteral("плошча"),
        QStringLiteral("пасёлак"),
        QStringLiteral("праезд"),
        QStringLiteral("праспект"),
        QStringLiteral("станцыя"),
        QStringLiteral("тунэль"),
        QStringLiteral("тупік"),
        QStringLiteral("افي."),
        QStringLiteral("إلى"),
        QStringLiteral("تسوية"),
        QStringLiteral("جادة"),
        QStringLiteral("جزيرة"),
        QStringLiteral("جسر"),
        QStringLiteral("زقاق"),
        QStringLiteral("شارع"),
        QStringLiteral("طريق"),
        QStringLiteral("قرية"),
        QStringLiteral("مأزق"),
        QStringLiteral("محطة"),
        QStringLiteral("مدينة"),
        QStringLiteral("مرور"),
        QStringLiteral("مسار"),
        QStringLiteral("ممر"),
        QStringLiteral("منطقة"),
        QStringLiteral("نفق"),
        QStringLiteral("път"),
        QStringLiteral("булевард"),
        QStringLiteral("град"),
        QStringLiteral("село"),
        QStringLiteral("кей"),
        QStringLiteral("островче"),
        QStringLiteral("платно"),
        QStringLiteral("квадрат"),
        QStringLiteral("пътуване"),
        QStringLiteral("произход"),
        QStringLiteral("гара"),
        QStringLiteral("тунел"),
        QStringLiteral("канал"),
        QStringLiteral("körút"),
        QStringLiteral("híd"),
        QStringLiteral("rakpart"),
        QStringLiteral("állomás"),
        QStringLiteral("alagút"),
        QStringLiteral("đường"),
        QStringLiteral("đại"),
        QStringLiteral("làng"),
        QStringLiteral("cầu"),
        QStringLiteral("đảo"),
        QStringLiteral("phố"),
        QStringLiteral("gốc"),
        QStringLiteral("kênh"),
        QStringLiteral("δρόμο"),
        QStringLiteral("λεωφόρος"),
        QStringLiteral("πόλη"),
        QStringLiteral("κωμόπολη"),
        QStringLiteral("χωριό"),
        QStringLiteral("δρόμος"),
        QStringLiteral("γέφυρα"),
        QStringLiteral("αποβάθρα"),
        QStringLiteral("νησί"),
        QStringLiteral("νησίδα"),
        QStringLiteral("λωρίδα"),
        QStringLiteral("πλατεία"),
        QStringLiteral("χωριό"),
        QStringLiteral("ταξίδια"),
        QStringLiteral("ø"),
        QStringLiteral("bane")
    };
    
    union CommonWords
    {
        static inline int getCommon(const QString name)
        {
            return WORDS.indexOf(name);
        }

        static inline int getCommonSearch(const QString name)
        {
            return WORDS.indexOf(name);
        }

        static inline int getCommonGeocoding(const QString name)
        {
            return WORDS.indexOf(name);
        }
    };
}

#endif // !defined(_OSMAND_CORE_COMMON_WORDS_H_)
