LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
PROJECT_ROOT_RELATIVE := ../../../../platforms/android/OsmAnd
OSMAND_QTBASE_ROOT_RELATIVE := ../../../externals/qtbase-android
OSMAND_QTBASE_ROOT := $(LOCAL_PATH)/$(OSMAND_QTBASE_ROOT_RELATIVE)
OSMAND_QTBASE_RELATIVE := ../../../externals/qtbase-android/upstream.patched
OSMAND_QTBASE := $(LOCAL_PATH)/$(OSMAND_QTBASE_RELATIVE)

ifeq ($(OSMAND_BUILDING_NEON_LIBRARY),true)
	OSMAND_QTBASE_SUFFIX := .$(TARGET_ARCH_ABI)-neon
	LOCAL_MODULE_SUFFIX := _neon
	LOCAL_ARM_NEON := true
else
	OSMAND_QTBASE_SUFFIX := .$(TARGET_ARCH_ABI)
	LOCAL_MODULE_SUFFIX :=
endif

include $(CLEAR_VARS)
LOCAL_MODULE := Qt5Core
LOCAL_SRC_FILES := $(OSMAND_QTBASE_RELATIVE)$(OSMAND_QTBASE_SUFFIX)/lib/lib$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX).so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := Qt5Network
LOCAL_SRC_FILES := $(OSMAND_QTBASE_RELATIVE)$(OSMAND_QTBASE_SUFFIX)/lib/lib$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX).so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := Qt5Xml
LOCAL_SRC_FILES := $(OSMAND_QTBASE_RELATIVE)$(OSMAND_QTBASE_SUFFIX)/lib/lib$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX).so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := Qt5Sql
LOCAL_SRC_FILES := $(OSMAND_QTBASE_RELATIVE)$(OSMAND_QTBASE_SUFFIX)/lib/lib$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX).so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := Qt5Concurrent
LOCAL_SRC_FILES := $(OSMAND_QTBASE_RELATIVE)$(OSMAND_QTBASE_SUFFIX)/lib/lib$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX).so
include $(PREBUILT_SHARED_LIBRARY)
